title: Upgrade Lightbeam Blog
author: Bianca Danforth
email: biancadanforth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Upgrade Lightbeam project blog for my web development internship with Mozilla.
twitter_username: biancadanforth
github_username: biancadanforth

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - 

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
- Gemfile.lock