title: Upgrade Lightbeam Blog
author: Bianca Danforth
email: biancadanforth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Upgrade Lightbeam project blog for my web development internship with Mozilla.
twitter_username: biancadanforth
github_username: biancadanforth
theme: minima